<?php
$collection = $block->getPostCollection();
if ($collection->count()) {
    ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('ID') ?></th>
                <th scope="col" class="col name"><?php echo __('Name') ?></th>
                <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
                <th scope="col" class="col-updated_at"><?php echo __('Update At') ?></th>
                <th scope="col" class="col action"><?php echo __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($collection as $item): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                        <?php echo $item->getId() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                        <?php echo $item->getName() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                        class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Updated At')) ?>" class="col-updated_at">
                    <?php echo $item->getUpdatedAt() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="col delete">
                        <a href="<?php echo $block->getDeleteAction() . 'id/' . $item->getId(); ?>"><?php echo __('Delete') ?></a>
                        <a style="margin-left: 9px"
                           href="<?php echo $block->getEditAction() . 'id/' . $item->getId(); ?>"><?php echo __('Edit') ?></a>
                    </td>

                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <td data-th="<?= $block->escapeHtml(__('Add')) ?>" class="col Add">
        <a href="<?php echo $block->getAddAction() . 'id/' . $item->getId(); ?>"><?php echo __('Add') ?></a></td>
    </div>
    <?php
}
?>
